<!DOCTYPE html>
<html  lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registration Form</title>
        <link rel="stylesheet" href="assets/css/main.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="assets/css/main.css">
</head>

    <body >

        <div class="container-fluid vh-100" style="background-image: url('assets/images/sgp.png');">
        
            <div class="" style="">
                <div class="rounded d-flex justify-content-center">
                    <div class="col-md-4 col-sm-12 shadow-lg p-5">
                        <div class="text-center">
                            <h3 class="text-white">Create Account</h3>
                        </div>
                        <div class="p-4">
                            <form action="" method="post">
                                <div class="input-group mb-3">
                                    <span class="input-group-text bg-transparent"><i
                                            class="bi bi-person-plus-fill text-white"></i></span>
                                    <input type="text" class="form-control" placeholder="Username">
                                </div>
                                <div class="input-group mb-3">
                                    <span class="input-group-text bg-transparent"><i
                                            class="bi bi-person-plus-fill text-white"></i></span>
                                    <input type="text" class="form-control" placeholder="Address">
                                </div>
                                <div class="input-group mb-3">
                                    <span class="input-group-text bg-transparent"><i
                                            class="bi bi-person-plus-fill text-white"></i></span>
                                    <input type="text" class="form-control" placeholder="Mobile">
                                </div>
                                <div class="input-group mb-3">
                                    <span class="input-group-text bg-transparent"><i
                                            class="bi bi-envelope text-white"></i></span>
                                    <input type="email" class="form-control" placeholder="Email">
                                </div>
                                <div class="input-group mb-3">
                                    <span class="input-group-text bg-transparent"><i
                                            class="bi bi-key-fill text-white"></i></span>
                                    <input type="password" class="form-control" placeholder="password">
                                </div>
                                <div class="d-grid col-12 mx-auto">
                                    <input class="btn bg-success text-warning" style="border: none; border-radius: 5px;" type="submit" value="Sign up"></input>
                                </div>
                                <p class="text-center mt-3 text-white">Already have an account?
                                    <a class="text-warning"href="login.php">Sign in</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>